language: "en"
intents:
  ConcatenatedSentences:
    data:
      - sentences:
          - "{sentence_1} (and[ then]|then) {sentence_2}"
        slots:
          language: "en"
lists:
  sentence_1:
    wildcard: true
  sentence_2:
    wildcard: true
